name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Авто-запуск в полночь
  workflow_dispatch:      # Кнопка ручного запуска

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
